<a href="https://colab.research.google.com/github/2003Yash/numpy-basics/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NUMPY is scientifc form of storing multi dimensional data arrays
# NUMPY is better than lists in python since comparitibely they are super fast than lists

# we usually put lists of python in an numpy array for faster processing

Basics

In [ ]:
#Getting numpy
import numpy as np

In [ ]:
#1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2D array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#Getting dimensions
b.ndim

2

In [ ]:
# Get Shape
b.shape

#(x,y) means x rows and y columns

(2, 3)

In [ ]:
# Get Type
a.dtype
#dtype means datatype

dtype('int64')

In [ ]:
c = np.array([1,2,3,4], dtype = "int32")

#we can explictly store values in lower bits(or) forms of int

In [ ]:
# Get Size
a.itemsize

8

In [ ]:
# Get total size
a.nbytes

# or a.itemsize * a.size

24

Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get everything in a specific row
# : defines everything
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
# or a[0, 1:6:2] , since 1 represents 2 and we end at 6th index or. -1 means foreveer

In [ ]:
# Changing items
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2] = [1,2]
a
#no need to explicitly write print in colab

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3D example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
b[0,1,1] #i.e to get to 4 we need first set of matrix inside 2 nd set 2nd item

4

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
b[:,1,:] = [[9,9],[8,8]]
b[:,1,:]

array([[9, 9],
       [8, 8]])

Initializing Different Types of Arrays

In [ ]:
# All 0s matrix and we just need to specify shape
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.ones((4,2,2), dtype='int32') #we can also specify the int format for space saving

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#to create a matrix of any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like) by using shape of other matrix
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.full_like(a.shape, 4) #since .shape itself returns a matirx as answer

array([4, 4])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.4992471 , 0.65020028],
       [0.21819778, 0.87073487],
       [0.75267793, 0.57314776],
       [0.15901107, 0.07330082]])

In [ ]:
# Random Integer values we are specifying range in first 2 parameters
np.random.randint(-4,8, size=(3,3)) # don't write shape it's size

array([[ 6,  4,  0],
       [ 0,  7, -3],
       [-2,  6,  0]])

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]]) #[] is vector [[]] is matrix
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
arr = np.array([[1,2,3]]) #[] is vector [[]] is matrix
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
# or output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Copying Arrays

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a) #change of b value also changes a value

[100   2   3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a) #use .copy to copy an array

[1 2 3]


Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a # a is not changed since we are doing a+2 but not a = a+2

array([1, 2, 3, 4])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
np.cos(a)
#np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

#matrix multiplication
#RULE: no.of columns of first matrix should be equal to no.of rows of second matrix
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)
#since det of indentity matirx is always 1

1.0

Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats) #min value

1

In [ ]:
np.max(stats)

6

In [ ]:
np.max(stats, axis=1) #get the max value column

array([3, 6])

In [ ]:
np.sum(stats) #sum of all

21

In [ ]:
np.sum(stats, axis=0) #sum of cols

array([5, 7, 9])

In [ ]:
np.sum(stats, axis=1) #sum of rows

array([ 6, 15])

Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
after = before.reshape((8,1)) #we can reshape array into any shape of same size
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

d = np.vstack([v1,v2,v1,v2])
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])